In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,100,60)

In [4]:
arr

array([71, 16, 67, 62, 22, 81, 24, 75, 27, 37, 59, 24, 66, 11, 27, 18, 68,
       28, 15, 49, 47, 65, 48, 32, 62, 82, 53, 57, 32, 27, 41, 90, 79, 96,
       37, 33, 72, 31, 52, 72, 96, 76,  9, 73, 44, 33, 70, 79,  2, 86, 73,
       28, 31, 61,  7, 22, 99, 82,  9, 40])

In [5]:
arr = arr.reshape(12,5)

In [6]:
arr

array([[71, 16, 67, 62, 22],
       [81, 24, 75, 27, 37],
       [59, 24, 66, 11, 27],
       [18, 68, 28, 15, 49],
       [47, 65, 48, 32, 62],
       [82, 53, 57, 32, 27],
       [41, 90, 79, 96, 37],
       [33, 72, 31, 52, 72],
       [96, 76,  9, 73, 44],
       [33, 70, 79,  2, 86],
       [73, 28, 31, 61,  7],
       [22, 99, 82,  9, 40]])

In [7]:
def array_func(arr):
    last_row = arr[-1]

    # max and min element

    max = last_row[0]
    min = last_row[0]
    for n in last_row:
        if n>max:
            max=n
        if n<min:
            min=n

    # Average
     
    avg = last_row.sum() / len(last_row)

    # No. of evens
    
    even = 0
    for i in last_row:
        if i%2 == 0:
            even+=1

    return (max,min, avg, even)

data = array_func(arr)
print(f'Last row of array : {arr[-1]}')
print(f'Max in last row : {data[0]}')
print(f'Min in last row : {data[1]}')
print(f'Average of elements in last row : {data[2]}')
print(f'No. of evens in last row : {data[3]}')

Last row of array : [22 99 82  9 40]
Max in last row : 99
Min in last row : 9
Average of elements in last row : 50.4
No. of evens in last row : 3


In [8]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr1[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])