In [1]:
import numpy as np
arr1 = np.random.randint(1,51,60).reshape(12,5)

In [2]:
arr1

array([[44,  7,  5, 35, 25],
       [49, 36, 47, 13, 22],
       [20, 12, 40, 33, 48],
       [33, 35, 28, 21, 35],
       [46, 20, 18, 11, 20],
       [50,  3, 20, 18, 19],
       [ 8, 29, 22, 19, 29],
       [ 3, 39,  5, 18, 36],
       [13, 22,  8, 24, 21],
       [50, 22, 36, 27, 44],
       [39, 22, 32, 29,  7],
       [15,  4, 44, 15, 19]])

In [3]:
arr1.ndim

2

In [4]:
arr1[11] #lastrow

array([15,  4, 44, 15, 19])

In [5]:
arr1

array([[44,  7,  5, 35, 25],
       [49, 36, 47, 13, 22],
       [20, 12, 40, 33, 48],
       [33, 35, 28, 21, 35],
       [46, 20, 18, 11, 20],
       [50,  3, 20, 18, 19],
       [ 8, 29, 22, 19, 29],
       [ 3, 39,  5, 18, 36],
       [13, 22,  8, 24, 21],
       [50, 22, 36, 27, 44],
       [39, 22, 32, 29,  7],
       [15,  4, 44, 15, 19]])

In [6]:
def max_n_min(arr):
    for i in range(len(arr)):
        j=0
        max=arr[i][j]
        min=arr[i][j]
        for num in arr[i]:
            if arr[i][j]>max:
                max=arr[i][j]
            if arr[i][j]<min:
                min=arr[i][j]
            j+=1
        print(f'For row {i+1}, max element : {max}  and min element : {min}' )

arr2 = np.random.randint(1,51,60).reshape(12,5)
arr2

array([[31, 35, 19,  3,  1],
       [23, 20, 20, 25, 14],
       [19,  2, 34,  3, 11],
       [32,  6, 47, 24, 11],
       [ 2, 25, 34, 41, 47],
       [40, 43, 21,  3, 27],
       [45, 25, 35, 15, 36],
       [50, 33, 37, 37, 31],
       [43, 25, 28, 42,  7],
       [38, 25, 12, 21,  1],
       [41, 39, 20, 28, 44],
       [36,  1, 22, 32, 49]])

In [7]:
max_n_min(arr2)

For row 1, max element : 35  and min element : 1
For row 2, max element : 25  and min element : 14
For row 3, max element : 34  and min element : 2
For row 4, max element : 47  and min element : 6
For row 5, max element : 47  and min element : 2
For row 6, max element : 43  and min element : 3
For row 7, max element : 45  and min element : 15
For row 8, max element : 50  and min element : 31
For row 9, max element : 43  and min element : 7
For row 10, max element : 38  and min element : 1
For row 11, max element : 44  and min element : 20
For row 12, max element : 49  and min element : 1
